config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :orders
  resources :ingredients
  resources :users
  resources :order_items do
    post :print
    post :print_sticker
    collection do
      post :multiple_prints
    end
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :order_item

  scope :deliver_quantity_in_date_between, ->(start_date, end_date) { joins(:order_item).select("ingredients.unit as ingredient_unit, ingredients.name as ingredient_name, SUM(ingredients.quantity * order_items.quantity) as ingredient_quantity").where(order_items: {delivery_date: start_date..end_date}).group('ingredient_name, ingredient_unit').order('ingredient_name') }
end

app/models/job.rb
class Job < ApplicationRecord

end

app/models/order.rb
class Order < ApplicationRecord
  after_create :process_order
  has_many :order_items
  has_many :ingredients, through: :order_items


  store_accessor :details, :total_price, :customer, :line_items, :tags, :billing_address

  def self.new_order_from_json(order_json)
    order = JSON.parse(order_json)
    new(name: order['name'],
        price: order['total_price'],
        customer_name: order['customer']['first_name']+ " " +order['customer']['last_name'],
        details: order,
    )
  end

  def self.new_order_from_hash(order_hash)
    new(name: order_hash.name,
        price: order_hash.total_price,
        customer_name: ((order_hash.customer.first_name+ " " +order_hash.customer.last_name) rescue ""),
        details: order_hash,
    )
  end

  def process_order
    self.line_items.each do |line_item|
      order_item = self.order_items.new(
          name: line_item['name'],
          price: line_item['price'],
          quantity: line_item['quantity'],
          product_id: line_item['product_id'],
          variant_id: line_item['variant_id'],
          delivery_date: (
          Date::strptime(line_item['properties'].select{ |property| property['name'] == 'Date' }.first['value'], "%m/%d/%y") rescue nil
          )
          # delivery_time: line_item['properties'].select{ |property| property['name'].gsub(/\W/,"") == 'Time' }.first['value']
      )

      _time = line_item['properties'].select{ |property| property['name'] == 'Time' }.first['value'] rescue nil
      if not _time.nil?
        order_item.start_time, order_item.end_time = _time.split('-')
      end
      order_item.save!
      line_item['properties'].each do |property|
        unless ["Date","Time"].include? property['name']
          quantity , unit = property['value'].split(' ')
          order_item.ingredients.create!(name: property['name'], quantity: quantity.to_f, unit: unit)
        end
      end
    end

  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  has_many :ingredients
  belongs_to :order

  scope :having_delivery_date_between, ->(start_date, end_date) { where(delivery_date: start_date..end_date) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  layout :layout_by_resource

  def index
    @search_delivery_date = (params[:search] and params[:search][:delivery_date] and params[:search][:delivery_date] != '' ) ? params[:search][:delivery_date] : "#{Date.today.beginning_of_month.strftime('%m/%d/%Y')} - #{Date.today.end_of_month.strftime('%m/%d/%Y')}"
    delivery_start, delivery_end = @search_delivery_date.split(' - ')
    @ingredients = Ingredient.deliver_quantity_in_date_between(Date.strptime(delivery_start, '%m/%d/%Y'), Date.strptime(delivery_end, '%m/%d/%Y'))
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/concerns/shopify_webhook.rb
module ShopifyWebhook
  extend ActiveSupport::Concern

  def verify_webhook(data, request)
    hmac_header = request.env['HTTP_X_SHOPIFY_HMAC_SHA256']
    calculated_hmac = Base64.strict_encode64(OpenSSL::HMAC.digest('sha256', ENV["webhook_token"], data))
    ActiveSupport::SecurityUtils.secure_compare(calculated_hmac, hmac_header)
  end

  def get_shop_name(request)
    request.env['HTTP_X_SHOPIFY_SHOP_DOMAIN'].partition(".").first.to_s
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @q = Ingredient.ransack(params[:q])
    @ingredients = @q.result.paginate(page: params[:page], per_page: 30)
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :find_order_item, only: [:print, :show, :print_sticker, :multiple_print]

  def index
    @q = OrderItem.joins(:order).ransack(params[:q])
    @order_items = @q.result
    @search_delivery_date = ''
    @search_created_date = ''
    if params[:search]
      if params[:search][:delivery_date] and params[:search][:delivery_date] != ''
        @search_delivery_date =  params[:search][:delivery_date]
        delivery_start, delivery_end = params[:search][:delivery_date].split(' - ')
        @order_items = @order_items.having_delivery_date_between(Date.strptime(delivery_start, '%m/%d/%Y'), Date.strptime(delivery_end, '%m/%d/%Y'))
      end

      if params[:search][:created_at] and params[:search][:created_at] != ''
        @search_created_date = params[:search][:created_at]
        created_start, created_end = params[:search][:created_at].split(' - ')
        @order_items = @order_items.where(orders: {created_at: DateTime.strptime(created_start, '%m/%d/%Y')..DateTime.strptime(created_end, '%m/%d/%Y')})
      end
    end
    @order_items = @order_items.paginate(page: params[:page], per_page: 30).decorate
  end

  def show
    @order = @order_item.order.decorate
  end

  def print

  end

  def print_sticker

  end

  def multiple_prints
    @order_items = OrderItem.where(id: params[:order_item_ids]).decorate || []
  end

  private

  def find_order_item
    @order_item = OrderItem.find_by_id(params[:id] || params[:order_item_id]).decorate
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except:[:create]

  skip_before_action :verify_authenticity_token ,only: [:create]

  include ShopifyWebhook


  def show
    @order = Order.find_by_id(params[:id]).decorate
  end

  # POST /orders (as webhooks from fambrand stores)
  def create
    request.body.rewind
    data = request.body.read
    verified = verify_webhook(data, request)
    if verified
      @order = Order.new_order_from_json(data)
      if @order.present?
        @order.save
        # @order.delay(:retry => false).save
        head :ok
      end
    else
      head :error
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :admin?

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save!
      flash[:success] = "User Successfully created."
    else
      flash[:errors] = @user.errors.full_messages
    end

    redirect_to users_path
  end

  private

  def admin?
    redirect_to root_url, notice: "You don't have permission to access this page." if not current_user.admin?
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.slim
= render 'shared/breadcrumbs', heading: 'Welcome To Green Top Farm Dashboard'
/! Main content
.row
  .col-xl-4.col-md-4.col
    .info-box
      span.info-box-icon.bg-orange
        i.ion.ion-person-stalker
      .info-box-content
        span.info-box-number.text-muted= User.count
        span.info-box-text.text-muted Total Users
  .col-xl-4.col-md-4.col
    .info-box
      span.info-box-icon.bg-orange
        i.ion.ion-android-more-horizontal
      .info-box-content
        span.info-box-number.text-muted= Order.count
        span.info-box-text.text-muted Total Orders
  .col-xl-4.col-md-4.col
    .info-box
      span.info-box-icon.bg-orange
        i.ion.ion-android-notifications
      .info-box-content
        span.info-box-number.text-muted= OrderItem.where('delivery_date < ?', Date.today ).count
        span.info-box-text.text-muted Pendind Orders
.row
  .col-md-12.col-lg-12
    .box
      .box-header.with-border
        h3.box-title List of Ingredients used in a given date range
      .box-body
        .row
          .col-12
            = form_for(:search, url: root_path, method: :get) do |f|
              .row
                .col-12
                  .form-group
                    .input-group
                      .input-group-addon
                        i.fa.fa-calendar
                      = f.text_field :delivery_date,  class: 'form-control', value: @search_delivery_date
              .col-12
                = f.submit "Search", class: 'btn btn-success pull-right'
        hr
        table.table.table-bordered.table-responsive
          tbody
            tr
              td #
              td Item
              th QTY
            - @ingredients.nil?
              tr
                td No record Found.
            - @ingredients.each_with_index do |ingredient, index|
              tr
                td= index + 1
                td= ingredient.ingredient_name
                td= "#{ingredient.ingredient_quantity} #{ingredient.ingredient_unit}"

app/views/ingredients/index.html.slim
= render 'shared/breadcrumbs', heading: 'Order Ingredients'
.row
  .col-12
    .box
      .box-header.with-border
        h3.box-title List of all Order Ingredients
      .box-body
        table.table.table-bordered.table-responsive
          tbody
            tr
              th Order
              th Customer Name
              th Ingredient Name
              th Item Name
              th= sort_link @q, :order_item_delivery_date
              th QTY
              th Created At
            - @ingredients.each do |ingredient|
              tr
                td= link_to ingredient.order_item.order.name, ingredient.order_item.order
                td= ingredient.order_item.order.customer_name
                td= link_to ingredient.name, '#'
                td= link_to ingredient.order_item.name, '#'
                td= ingredient.order_item.delivery_date
                td #{ingredient.quantity * ingredient.order_item.quantity } #{ingredient.unit}
                td= ingredient.order_item.order.created_at.strftime('%b %d, %Y %I:%M %P')
      .box-footer.clearfix
        = will_paginate(@ingredients, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)

app/views/layouts/application.html.slim
doctype html
html
  = render 'shared/head'
  = render 'shared/scripts'
  body.hold-transition.skin-orange-light.sidebar-mini
    .wrapper
      = render 'shared/header'
      = render 'shared/aside'
      .content-wrapper
        = yield :breadcrumbs
        section.content
          = yield
      = render 'shared/footer'
    .remote_container
    .hide
      #hidden_remote_container

app/views/layouts/devise.html.slim
doctype html
html
  = render 'shared/head'
  body.hold-transition.login-page
    = render 'shared/flash'
    = yield
  = render 'shared/scripts'

app/views/order_items/index.html.slim
= javascript_include_tag 'dymo3'
= javascript_include_tag 'dynmo_print'
= render 'shared/breadcrumbs', heading: 'Package'
= render 'order_items/partials/search', search: @q
.row
  .col-12
    .box
      .box-header.with-border
        .row
          .col-6
            h3.box-title List of all Packages
          .col-6
            = button_tag "Print Kitchen Recipts", data: { disable_with: "Printing..." }, class: 'btn btn-warning btn-lg bg-orange pull-right', id: 'btn-print-kitchen', style: 'margin-left: 10px;'
            = button_tag "Print Stickers", data: { disable_with: "Printing..." }, class: 'btn btn-warning btn-lg bg-orange pull-right', id: 'btn-print-stickers'
      .box-body
        table.table.table-bordered.table-responsive
          tbody
            tr
              td
              th Order
              th Company
              th Package
              th= sort_link @q, :delivery_date
              th Delivery time
              th QTY
              th Price
              th Action
            = form_tag multiple_prints_order_items_path, id: 'multiple-print-form',  method: :post, remote: true
            = hidden_field_tag :print_type, ''
            - @order_items.nil?
              tr
                td No record Found.
            - @order_items.each do |order_item|
              tr
                td
                  .checkbox
                    input name="order_item_ids[]" type="checkbox" value="#{order_item.id}" id="#{dom_id(order_item)}"
                    label for= "#{dom_id(order_item)}"
                td= link_to order_item.order.name, order_item.order
                td= order_item.order.decorate.company_name
                td= link_to order_item.name, order_item
                td= order_item.formated_delivrey_date
                td= order_item.formated_delivery_time
                td= order_item.quantity
                td= number_to_currency order_item.price
                td
                  = link_to order_item_print_sticker_path(order_item), class: 'btn btn-blue pull-right', method: :post, remote: true do
                    span
                      i.fa.fa-print
                      |  Print Sticker
      .box-footer.clearfix
        = will_paginate(@order_items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)

app/views/order_items/multiple_prints.js.slim
| $( "#hidden_remote_container" ).empty();
- if params[:print_type] == "kitchen"
    - @order_items.each do |order_item|
        | $("#hidden_remote_container").append("#{escape_javascript(render 'order_items/partials/invoice', order_item: order_item.decorate, order: order_item.order.decorate)}");
    | doPrint("#hidden_remote_container");

app/views/order_items/partials/_invoice.html.slim
.invoice.printableArea.print-kitchen-recipt style=("margin-right: 0px !important; margin-left: 0px !important;")
  .row
    .col-12
      h2.page-header
        | ORDER # #{order.name}
        small.pull-right Delivery Date: #{order_item.formated_delivrey_date}
  /! /.col
  .row.invoice-info
    .col-6
      address
        strong.text-orange #{order_item.name}
        br
        | Time to Leave: #{order_item.delivery_time}
        br
        | QTY: #{order_item.quantity}
    .col-6.text-right
      | To
      address
        strong.text-orange #{order.customer_name}
        br
        | Email: #{order.contact_email}
  .row
    .col-sm-12
      p.lead
        b Notes:
        p.text-muted.well.well-sm.no-shadow style=("margin-top: 10px;")
          = order.note
  hr
  .row
    .col-12.table-responsive
      table.table.table-striped
        thead
          tr
            th #
            th Item
            th Quantity
        tbody
          - i = 0
          - if order_item.ingredients.empty?
            tr
              td= i = i +1
              td= order_item.name
              td= order_item.quantity
          - else
            - order_item.ingredients.each do |ingredient|
              tr
                td= i = i +1
                td= ingredient.name
                td #{(ingredient.quantity * ingredient.order_item.quantity).round(1) } #{ingredient.unit}
  .row
    .col-12.col-sm-12
      p.text-red.pull-right style=("margin-top: 10px; font-style: italic; font-size: 11px;")
        | All Items need to be checked after they are packed before leaving for devlivery.
    / .col-12.col-sm-6.text-right
      .total-payment
        h3
          b Total Price:
          = number_to_currency order.total_price_usd
.clearfix

app/views/order_items/partials/_search.html.slim
.row
  .col-12
    .box.box-default
      .box-header.with-border
        h3.box-title Filters
        .box-tools.pull-right
          button.btn.btn-box-tool data-widget="collapse" type="button"
            i.fa.fa-minus
          button.btn.btn-box-tool data-widget="remove" type="button"
            i.fa.fa-remove
      /! /.box-header
      .box-body
        .row
          .col-12
            = form_for(:search, url: order_items_path, method: :get) do |f|
              .row
                .col-6
                  .form-group
                    label Delivery Date:
                    .input-group
                      .input-group-addon
                        i.fa.fa-calendar
                      = f.text_field :delivery_date,  class: 'form-control', value: @search_delivery_date
                .col-6
                  .form-group
                    label Created At:
                    .input-group
                      .input-group-addon
                        i.fa.fa-calendar
                      = f.text_field :created_at,  class: 'form-control', value: @search_created_date
              hr
              .col-12
                = f.submit "Search", class: 'btn btn-success pull-right'

app/views/order_items/partials/_sticker.html.slim
.printableArea.print-sticker-recipt.invoice1
  .row
    .col-12
      .row
        .col-6
          .box.box-widget.widget-user-4
            .widget-user-header
              .overlay
                h3.widget-user-username.font-size-16= order.customer_name
                h6.widget-user-desc.font-size-14= order.company_name
            .box-footer
              .row
                .col-4.border-right
                  .description-block
                    h5.description-header.font-size-10 Order#
                    span.description-text.font-size-10= order.name
                .col-4.border-right
                  .description-block
                    span.description-text.font-size-10= order_item.name
                .col-4
                  .description-block
                    h5.description-header.font-size-10 Quantity
                    span.description-text.font-size-10= order_item.quantity
        - order_item.ingredients.each do |ingredient|
          .col-6
            .box.box-widget.widget-user-4
              .widget-user-header
                .overlay
                  h3.widget-user-username.font-size-16= order.customer_name
                  h6.widget-user-desc.font-size-14= order.company_name
              .box-footer
                .row
                  .col-4.border-right
                    .description-block
                      h5.description-header.font-size-10 Order#
                      span.description-text.font-size-10= order.name
                  .col-4.border-right
                    .description-block
                      span.description-text.font-size-10= ingredient.name
                  .col-4
                    .description-block
                      h5.description-header.font-size-10 Quantity
                      span.description-text.font-size-10= order_item.quantity

app/views/order_items/print.js.slim
| $("#hidden_remote_container").html("#{escape_javascript(render 'order_items/partials/invoice', order_item: @order_item.decorate, order: @order_item.order.decorate)}");
| printable();

app/views/order_items/print_sticker.js.slim
| $("#hidden_remote_container").html("#{escape_javascript(render 'order_items/partials/sticker', order_item: @order_item.decorate, order: @order_item.order.decorate)}");
|  doPrint(".print-sticker-recipt");

app/views/order_items/show.html.slim
= render 'shared/breadcrumbs', heading: "Package:  #{@order_item.name}"
/ .row.no-print
  .col-12
    button#print-sticker.btn.btn-blue.pull-right type="button"
      span
        i.fa.fa-print
        |  Print Sticker
  .col-12.margin-top-10
    = render 'order_items/partials/sticker', order: @order, order_item: @order_item
.row.no-print
  .col-12
    button#print.btn.btn-blue.pull-right type="button"
      span
        i.fa.fa-print
        |  Print Kitchen Receipt
  .col-12
    = render 'order_items/partials/invoice', order: @order, order_item: @order_item

app/views/orders/show.html.slim
= render 'shared/breadcrumbs', heading: "Order # #{@order.name}"
.row
  .col-12
    .box.box-widget.widget-user-4
      .widget-user-header
        .overlay
          .widget-user-image
          h3.widget-user-username= @order.customer_name
          / h6.widget-user-desc= @order.note
      .box-footer
        .row
          .col-4.border-right
            .description-block
              h5.description-header Created At
              span.description-text= @order.created_at.strftime('%b %d, %Y %I:%M %P')
          .col-4.border-right
            .description-block
              h5.description-header Contact Email
              span.description-text= @order.contact_email
          .col-4
            .description-block
              h5.description-header Phone
              span.description-text= @order.phone

        .row.margin-top-10
          .col-4.border-right
            .description-block
              h5.description-header No. of Order Items
              span.description-text= @order.order_items.count
          .col-4.border-right
            .description-block
              h5.description-header Notes
              span.description-text= @order.note
          .col-4
            .description-block
              h5.description-header Total Price
              span.description-text= number_to_currency @order.price
.row
  .col-12
    .box
      .box-header.with-border
        h3.box-title List of Packages
      .box-body
        table.table.table-bordered.table-responsive
          tbody
            tr
              th Package Name
              th QTY
              th Delivery Date
              th Delivery Time
              th Price
              th Action
            - @order.order_items.each do |order_item|
              tr
                td= link_to order_item.name, order_item
                td= order_item.quantity
                td= order_item.delivery_date
                td= order_item.start_time.strftime("%I:%M%p").to_s + "-" + order_item.end_time.strftime("%I:%M%p").to_s rescue ""
                td= number_to_currency order_item.price
                td
                  = link_to order_item_print_path(order_item), class: 'btn btn-blue margin-right-10', method: :post, remote: true do
                    span
                      i.fa.fa-print
                      |  Print Kitchen Recipt
                  = link_to order_item_print_sticker_path(order_item), class: 'btn btn-blue', method: :post, remote: true do
                    span
                      i.fa.fa-print
                      |  Print Sticker

app/views/shared/_aside.html.slim
/! Left side column. contains the logo and sidebar
aside.main-sidebar
  /! sidebar
  section.sidebar
    /! Sidebar user panel
    .user-panel
      .image.float-left
        = image_tag 'logo2.png', class: 'rounded-circle'
      / .info.float-left
        p= current_user.email
        / a href="#"
          i.fa.fa-circle.text-success
          | Online
      /! search form
      form.sidebar-form action="#" method="get"
        .input-group
          input.form-control.hidden name="q" placeholder="Search..." type="text" /
          span.input-group-btn
            button#search-btn.btn.btn-flat name="search" type="submit"
              i.fa.fa-search
    /! /.search form
    /! sidebar menu
    ul.sidebar-menu data-widget="tree"
      li
        a href="#{root_path}"
          i.fa.fa-dashboard
          span Dashboard
      - if current_user.admin?
        li
          a href="#{users_path}"
            i.fa.fa-users
            span Users
      li
        a href="#{order_items_path}"
          i.fa.fa-table
          span Orders by Product
  .sidebar-footer
    = link_to(raw("<i class='fa fa-power-off'></i>"), destroy_user_session_path, method: :delete, class: 'link pull-right right', data: {toggle: "tooltip", "original-title": "Logout"})

app/views/shared/_breadcrumbs.html.slim
= content_for :breadcrumbs do
  section.content-header
    h1
      = heading
      / small Control panel
    ol.breadcrumb
      li.breadcrumb-item
        a href="#{root_path}"
          i.fa.fa-dashboard
          | Home
      li.breadcrumb-item.active= heading

app/views/shared/_flash.html.slim
- if flash[:alert].present? || flash[:toastr].present? || flash[:error].present? || flash[:errors].present? || flash[:success].present? || flash[:notice].present? || flash[:info].present?
  javascript:
    $(document).ready(function () {
      $(window).load(function() {
        if("#{flash[:error].present?}" == "true"){
          flash_success("#{flash[:error]}");
        }
        else if("#{flash[:success].present?}" == "true"){
          flash_success("#{flash[:success]}");
        }
        else if("#{flash[:info].present?}" == "true"){
          flash_info("#{flash[:info]}");
        }
        else if("#{flash[:alert].present?}" == "true"){
          flash_alert("#{flash[:alert]}");
        }
        else if("#{flash[:notice].present?}" == "true"){
            flash_info("#{flash[:notice]}");
        }else if("#{flash[:errors].present?}" == "true"){
          $.each(#{flash[:errors] || []}, function( index, value ) {
            flash_error(value);
          });
        }
      });
    });

app/views/shared/_footer.html.slim
footer.main-footer
  .pull-right.d-none.d-sm-inline-block
  | Copyright &copy; 2018
  a href="#{root_path}"  Green Top Farms
  |  All Rights Reserved.

app/views/shared/_head.html.slim
head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
  title 
    | Green top Farms
  = favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon"
  = csrf_meta_tags
  = csp_meta_tag
  = render 'shared/stylesheets'

app/views/shared/_scripts.html.slim
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= render 'shared/flash'

app/views/shared/_stylesheets.html.slim
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css'
link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" /

app/views/users/_user.html.slim
tr id=("user-#{user.id}")
  td= user.email

app/views/users/index.html.slim
= render 'shared/breadcrumbs', heading: 'Users'
.row
  .col-12
    .box
      .box-header.with-border
        .row
          .col-6
            h3.box-title List of all Users
          .col-6
            = link_to 'New', new_user_path, remote: true, class: 'btn btn-warning btn-lg bg-orange pull-right'
      .box-body
        table.table.table-bordered.table-responsive
          tbody
            tr
              th Email
            = render @users
        = will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)

app/views/users/new.js.slim
| $(".remote_container").html("#{escape_javascript(render 'users/partials/modal', user: @user)}");
| $("#myModal").modal('toggle');

app/views/users/partials/_modal.html.slim
#myModal.modal.fade role="dialog"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title Create New User
      = simple_form_for user do |f|
        .modal-body
          = f.input :email, class: 'form-control required', placeholder: 'Enter email'
          = f.input :password, class: 'form-control required', placeholder: 'Enter Password'
        .modal-footer
          button.btn.btn-lg.pull-left data-dismiss="modal" type="button"  Close
          = f.button :submit, class: 'btn btn-warning btn-lg bg-orange'